<a href="https://colab.research.google.com/github/padmaja-gadiraju/ml-lab/blob/main/19b01a1237_Machine_Learning_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

*Q1. Write python program for consider two random array A and B, check if they
are equal.*

In [ ]:
A = np.random.randint(0,4,5)
print("First array", A)
B = np.random.randint(0,4,5)
print("Second array", B)
check = np.allclose(A,B)
print(check)

First array [2 1 2 0 0]
Second array [0 0 0 1 3]
False


Q2. Write python program for consider a given vector, how to add 1 to each
element indexed by a second vector (be careful with repeated indices)?*

In [ ]:
A = np.random.randint(0,4,5)
print("Vetor : ", A)
B = np.random.randint(0,4,5)
print("Indices : ", B)
res = np.add.at(A,B,1)
print("Result", A)

Vetor :  [1 3 0 1 0]
Indices :  [3 0 2 1 1]
Result [2 5 1 2 0]


*Q3. Write python program to get the n largest values of an array.*

In [ ]:
arr = np.random.randint(2,25,10)
print("Array: ",arr)
arr1 = np.argsort(arr)
print("Sorted Array: ",arr[arr1])
n = int(input())
print(arr[arr1[-n:]])

Array:  [23  3  9  3 21 13  6 19 23 15]
Sorted Array:  [ 3  3  6  9 13 15 19 21 23 23]
8
[ 6  9 13 15 19 21 23 23]


*Q4. Load the energy data from the file `Energy Indicators.xls`, which is a list of
indicators of [energy supply and renewable electricity production]
(Energy%20Indicators.xls) from the
(http://unstats.un.org/unsd/environment/excel_file_tables/2013/Energy%20I
ndicators.xls) for the year 2013, and should be put into a DataFrame with the
variable name of **energy**.*

In [ ]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [ ]:
pip install --upgrade xlrd

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_excel ('EnergyIndicators.xls')
df = df[17:244]
df = df.drop(df.columns[[0,1]],axis = 1)
df = df.rename(columns={'Unnamed: 2':'Country','Unnamed: 3':'Energy','Unnamed: 4':'Energy Per Capita','Unnamed: 5':'Renewable Electricity'})
df.replace('...',np.nan,inplace = True)
df['Energy'] = df['Energy'].fillna(df['Energy'].mean())
df['Energy Per Capita'] = df['Energy Per Capita'].fillna(df['Energy Per Capita'].mean())
df['Renewable Electricity'] = df['Renewable Electricity'].fillna(df['Renewable Electricity'].mean())
name = input("Enter Country name: ")
ans = df[df['Country'] == name] 
print(ans)
print("For",name,"Energy is",ans['Energy'].to_string(index=False))

Enter Country name: India
    Country   Energy  Energy Per Capita  Renewable Electricity
113   India  33195.0               26.0               14.96908
For India Energy is 33195.0


*Q5. Write python program for given an arbitrary number of vectors, build the
cartesian product (every combinations of every item)*

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5])
res = np.transpose([np.tile(x, len(y)), np.repeat(y, len(x))])
print("Cartesian Product for Two Arrays:")
print(res)

Cartesian Product for Two Arrays:
[[1 4]
 [2 4]
 [3 4]
 [1 5]
 [2 5]
 [3 5]]


In [ ]:

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    print("Arrays: \n",arrays)
    
    shape = (len(x) for x in arrays)
    

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

arr1=[1, 2, 3]
arr2=[4,5]
arr3=[6,7]
arr4=[8,9,0]
res=cartesian((arr1, arr2, arr3,arr4))
print("Cartesian Product for Multiple Arrays: \n", res)

Arrays: 
 [array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9, 0])]
Cartesian Product for Multiple Arrays: 
 [[1 4 6 8]
 [1 4 6 9]
 [1 4 6 0]
 [1 4 7 8]
 [1 4 7 9]
 [1 4 7 0]
 [1 5 6 8]
 [1 5 6 9]
 [1 5 6 0]
 [1 5 7 8]
 [1 5 7 9]
 [1 5 7 0]
 [2 4 6 8]
 [2 4 6 9]
 [2 4 6 0]
 [2 4 7 8]
 [2 4 7 9]
 [2 4 7 0]
 [2 5 6 8]
 [2 5 6 9]
 [2 5 6 0]
 [2 5 7 8]
 [2 5 7 9]
 [2 5 7 0]
 [3 4 6 8]
 [3 4 6 9]
 [3 4 6 0]
 [3 4 7 8]
 [3 4 7 9]
 [3 4 7 0]
 [3 5 6 8]
 [3 5 6 9]
 [3 5 6 0]
 [3 5 7 8]
 [3 5 7 9]
 [3 5 7 0]]


*Q6 Write python program to get value of x for given linear equations.*

In [ ]:
from sympy import symbols, Eq, solve
x, y, z = symbols('x,y,z')
eq1 = Eq((x+y+z), 1)
print("Equation 1: ", eq1)
eq2 = Eq((x-y+2*z), 1)
print("Equation 2: ",eq2)
eq3 = Eq((2*x-y+2*z), 1)
print("Equation 3: ",eq3)
print("\n Values of 3 unknown variable are as follows:")
print(solve((eq1, eq2, eq3), (x, y, z)))

Equation 1:  Eq(x + y + z, 1)
Equation 2:  Eq(x - y + 2*z, 1)
Equation 3:  Eq(2*x - y + 2*z, 1)

 Values of 3 unknown variable are as follows:
{x: 0, y: 1/3, z: 2/3}


model 2

In [ ]:
from sympy import symbols, Eq, solve
x2 = int(input("Enter coefficient x2: "))
y2 = int(input("Enter coefficient y2: "))
c = int(input("Enter constant c: "))
x1 = int(input("Enter coefficient x1: "))
y1 = int(input("Enter coefficient y1: "))
c1 = int(input("Enter constant c1: "))
x,y = symbols('x y')
eq1 = Eq((x2*x)+(y2*y)+c,0)
eq2 = Eq((x1*x)+(y1*y)+c1,0)
solve((eq1,eq2),(x,y))

Enter coefficient x2: 2
Enter coefficient y2: 3
Enter constant c: 5
Enter coefficient x1: 3
Enter coefficient y1: 5
Enter constant c1: 6


{x: -7, y: 3}

*Q7. Write python program to find eigen analysis for given matrix.*

In [ ]:
m = np.mat("3 -2;1 0")
#print("Original matrix:", m)
w, v = np.linalg.eig(m) 
print( "Eigenvalues of W : ",w)
print( "Eigenvectors of V : ",v)

Eigenvalues of W :  [2. 1.]
Eigenvectors of V :  [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


*Q8. Write oython program to predict the age of the abalone by using MNIST data set.*